import { env, getApiBaseUrl, getAuthWebUrl, getDefaultRedirectUrl, getPublicWebsiteUrl } from "@/config/env";

export const appConfig = {
  name: env.appName,
  brandName: env.brandName,
  legalEntityName: env.legalEntityName,
  tagline: env.tagline,
  emails: {
    support: env.supportEmail,
    privacy: env.privacyEmail,
    security: env.securityEmail,
  },
  environment: env.appEnv,
  urls: {
    publicWebsite: getPublicWebsiteUrl(),
    authWebsite: getAuthWebUrl(),
    apiBase: getApiBaseUrl(),
    defaultRedirect: getDefaultRedirectUrl(),
  },
  routes: {
    home: "/",
    about: "/about",
    contact: "/contact",
    support: "/support",
    privacyPolicy: "/privacy-policy",
    termsOfService: "/terms-of-service",
    cookiePolicy: "/cookie-policy",
    socialLoginInformation: "/social-login-information",
    security: "/security",
    accountDeletion: "/account-deletion",
    dataDeletion: "/data-deletion",
    dataDeletionStatus: "/data-deletion/status/[confirmationCode]",
    login: "/auth/login",
    register: "/auth/register",
    verifyOtp: "/auth/verify-otp",
    forgotPassword: "/auth/forgot-password",
    resetPassword: "/auth/reset-password",
    logout: "/auth/logout",
    oauthAuthorize: "/oauth/authorize",
    oauthConsent: "/oauth/consent",
    oauthCallback: "/oauth/callback",
    account: "/account",
    accountSecurity: "/account/security",
  },
} as const;
